
export const sm = (style: string): string => style.split(' ').map(s => `sm:${s}`).join(' ')
export const md = (style: string): string => style.split(' ').map(s => `md:${s}`).join(' ')
export const lg = (style: string): string => style.split(' ').map(s => `lg:${s}`).join(' ')
export const xl = (style: string): string => style.split(' ').map(s => `xl:${s}`).join(' ')
export const _2xl = (style: string): string => style.split(' ').map(s => `2xl:${s}`).join(' ')
export const _3xl = (style: string): string => style.split(' ').map(s => `3xl:${s}`).join(' ')
export const _4xl = (style: string): string => style.split(' ').map(s => `4xl:${s}`).join(' ')
export const _5xl = (style: string): string => style.split(' ').map(s => `5xl:${s}`).join(' ')
export const _6xl = (style: string): string => style.split(' ').map(s => `6xl:${s}`).join(' ')
export const _7xl = (style: string): string => style.split(' ').map(s => `7xl:${s}`).join(' ')
export const _8xl = (style: string): string => style.split(' ').map(s => `8xl:${s}`).join(' ')
export const _9xl = (style: string): string => style.split(' ').map(s => `9xl:${s}`).join(' ')
